<?php


namespace MpAssocies\Exception;


use MyCLabs\Enum\Enum;

class Errors extends Enum
{
    // Auth exceptions
    const LOGIN_ERROR = 'LOGIN_ERROR';
    const UNAUTHORIZED = 'UNAUTHORIZED';
    const EXPIRED_TOKEN = 'EXPIRED_TOKEN';

    //Generic errors
    const UNKNOWN_ERROR = 'UNKNOW_ERROR';
    const MODEL_NOT_FOUND = 'MODEL_NOT_FOUND';
    const ERROR_FORM_VALIDATION = 'ERROR_FORM_VALIDATION';
    const LARAVEL_HTTP_EXCEPTION = 'LARAVEL_HTTP_EXCEPTION';
    const ERROR_DESERIALIZE_OBJECT = 'ERROR_DESERIALIZE_OBJECT';

    //Generic form errors
    const MISSING_FIELD = 'MISSING_FIELD';
    const STRING_BAD_FORMAT = 'STRING_BAD_FORMAT';
    const JSON_BAD_FORMAT = 'JSON_BAD_FORMAT';
    const BOOLEAN_BAD_FORMAT = 'BOOLEAN_BAD_FORMAT';
    const INTEGER_BAD_FORMAT = 'INTEGER_BAD_FORMAT';
    const VIOLATION_INTEGER_MIN = 'VIOLATION_INTEGER_MIN';
    const VIOLATION_INTEGER_DIGITS = 'VIOLATION_INTEGER_DIGITS';
    const HOUR_BAD_FORMAT = 'HOUR_BAD_FORMAT';
    const MINUTES_BAD_FORMAT = 'MINUTES_BAD_FORMAT';
    const DAY_BAD_FORMAT = 'DAY_BAD_FORMAT';
    const BAD_FORMAT_DATE = 'BAD_FORMAT_DATE';

    // laravel-form errors
    const FORM_MODULE_TITLE_TYPE_BAD_FORMAT = 'FORM_MODULE_TITLE_TYPE_BAD_FORMAT';
    const FORM_INPUT_TYPE_BAD_FORMAT = 'FORM_INPUT_TYPE_BAD_FORMAT';
    const FORM_FORM_DOESNT_EXISTS = 'FORM_DOESNT_EXISTS';
    const FORM_SHEET_DOESNT_EXISTS = 'SHEET_DOESNT_EXISTS';
    const FORM_ARRAY_DOESNT_EXISTS = 'ARRAY_DOESNT_EXISTS';
    const FORM_CHECKBOX_DOESNT_EXISTS = 'CHECKBOX_DOESNT_EXISTS';
    const FORM_SUBMISSION_DOESNT_EXISTS = 'SUBMISSION_DOESNT_EXISTS';
    const FORM_BLOC_DOESNT_EXISTS = 'BLOC_DOESNT_EXISTS';

    //laravel-calendar errors
    // Calendar errors
    const CALENDAR_CREATE_CONFLICT = 'CALENDAR_CREATE_CONFLICT';
    const CALENDAR_NOT_FOUND = 'CALENDAR_NOT_FOUND';
    const CALENDAR_EVENT_CONFLICT_OTHER_EVENT = 'CALENDAR_EVENT_CONFLICT_OTHER_EVENT';
    const CALENDAR_EVENT_NOT_FOUND = 'CALENDAR_EVENT_NOT_FOUND';
    const CALENDAR_DISPONIBILITY_NOT_FOUND = 'CALENDAR_DISPONIBILITY_NOT_FOUND';
    const CALENDAR_MEETING_NOT_FOUND = 'CALENDAR_MEETING_NOT_FOUND';

}